#+TITLE: Create a VLEAD OpenVZ template with git
#+AUTHOR: VLEAD
#+DATE: [2017-11-06 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document lists steps to create an OpenVZ
  template with the latest git version.  This template is
  built from the base template.

* Requirements
  1. All requirements from [[./create-centos-6-9-base-template.org][base template]].
  2. Install git 2.7.4

* Steps
** Create Container
   Choose template =centos-6.9-x86-base= whose
   url is
   =http://files.vlabs.ac.in/downloads/templates/centos-6.9-x86-base.tar.gz=
   and follow the steps listed in
   [[./create-container-from-template.org][create-container-from-template]].

** Install git 2.7.4
   Latest git is installed from the sources.  Please refer
   [[https://stackoverflow.com/questions/21820715/how-to-install-latest-version-of-git-on-centos-6-x-7-x][here]]. 
   - Steps:
     1. Login to the container that is created from the
        above steps and set the proxy. 
        #+BEGIN_EXAMPLE
        su -
        export http_proxy="http://proxy.iiit.ac.in:8080"
        export https_proxy="http://proxy.iiit.ac.in:8080"
        #+END_EXAMPLE
     2. Install Required Packages
        #+BEGIN_EXAMPLE
        yum install curl-devel expat-devel gettext-devel openssl-devel zlib-devel -y
        yum install  gcc perl-ExtUtils-MakeMaker -y
        #+END_EXAMPLE
     3. Uninstall old Git RPM
        #+BEGIN_EXAMPLE
        yum remove git
        #+END_EXAMPLE
     4. Download and Compile Git Source
        #+BEGIN_EXAMPLE
        cd /usr/src
        wget https://www.kernel.org/pub/software/scm/git/git-2.7.4.tar.gz
        tar xzf git-2.7.4.tar.gz
        #+END_EXAMPLE
     5. Compile sources
        #+BEGIN_EXAMPLE
        cd git-2.7.4
        make prefix=/usr/local/git all
        make prefix=/usr/local/git install
        echo 'export PATH=$PATH:/usr/local/git/bin' >> /etc/bashrc
        source /etc/bashrc
        #+END_EXAMPLE
     6. Check git version
        #+BEGIN_EXAMPLE
        git --version
        #+END_EXAMPLE

** Create template
   After customization is done, 
   1. exit the container and 
   2. create the template
      =centos-6.9-x86-base-with-git.tar.gz= from the base
      machine. Follow the [[https://github.com/vlead/vlead-templates/blob/develop/src/openvz-templates/create-template-from-container.org][steps]] to create the template.
