#+TITLE: Create a VLEAD base open VZ template
#+AUTHOR: VLEAD
#+DATE: [2017-11-06 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document lists steps to create a base open VZ
  template for VLEAD running centos 6.9. 

* Requirements
  1. Install 6.9 version of CentOS operating system.
  2. Support to install third party software
  3. Install Emacs for developer environment.  Here version
     is not important.
  4. Install network utilities

* Steps
** Create the machine from a template
   
   1. Download the template from the internet.  The template
      to be downloaded should have =centos 6= operating
      system.
      #+BEGIN_EXAMPLE
      wget http://download.openvz.org/template/precreated/centos-6-x86-minimal.tar.gz
      #+END_EXAMPLE

   2. Create a machine with the above template.

      #+BEGIN_EXAMPLE
      vzctl create <ctid>  --ostemplate <ostemplate> --diskspace <diskspace> --hostname <hostname> --ipadd <ipaddress>
      #+END_EXAMPLE

      #+BEGIN_EXAMPLE
      vzctl create 1245  --ostemplate centos-6-x86-minimal --diskspace 10G:15.0G --hostname centos-template.vlabs.ac.in --ipadd 10.4.12.45
      #+END_EXAMPLE

  3.  Start the newly created container

     #+BEGIN_EXAMPLE
     vzctl start <ctid>
     #+END_EXAMPLE

     #+BEGIN_EXAMPLE
     vzctl start 1245
     #+END_EXAMPLE

  4. Login to the machine
     #+BEGIN_EXAMPLE
     vzctl enter <ctid>
     #+END_EXAMPLE

     #+BEGIN_EXAMPLE
     vzctl enter 1245
     su -
     #+END_EXAMPLE

** Update the machine
   After creation of machine, set the proxy and install all
   updates.

   Steps:
   1. Set proxy
      #+BEGIN_EXAMPLE
      export http_proxy="http://proxy.iiit.ac.in:8080"
      export https_proxy="http://proxy.iiit.ac.in:8080"
      #+END_EXAMPLE
   2. Update 
      #+BEGIN_EXAMPLE
       yum update -y
      #+END_EXAMPLE

** Install [[https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiA1t_J16nXAhXKP48KHQeoBiwQFgglMAA&url=https%253A%252F%252Ffedoraproject.org%252Fwiki%252FEPEL&usg=AOvVaw1yI5PuhryGSuc3tbA5koOK][EPEL]]
   Enable REPL by executing the following [[https://www.liquidweb.com/kb/enable-epel-repository/][commands]]. 
   #+BEGIN_EXAMPLE
   yum install epel-release -y
   #+END_EXAMPLE

** Install emacs
   Emacs is an editor.  Installation of emacs is necessary
   since VLEAD's default editor is emacs.
   #+BEGIN_EXAMPLE
   yum install emacs -y
   #+END_EXAMPLE
   The above command will install emacs with version 23.x
** Install [[http://www.linuxfromscratch.org/blfs/view/svn/basicnet/bind-utils.html][bind-utils]]
   [[https://wiki.linuxfoundation.org/networking/net-tools][net-tools]] are already installed. Installing bind-utils
   will install =dig=, =host= and =nslookup=
   #+BEGIN_EXAMPLE
   yum install bind-utils -y
   #+END_EXAMPLE
   
** Create template
   After customization is done, 
   1. exit the container and 
   2. create the template =centos-6.9-x86-base.tar.gz= from
      the base machine. Follow the [[https://github.com/vlead/vlead-templates/blob/develop/src/openvz-templates/create-template-from-container.org][steps]] to create the
      template.
